name = "curiocity-apex"
main = "src/index.ts"
compatibility_date = "2024-01-26"

[[d1_databases]]
binding = "DB"
database_name = "curiocity-apex-db"
database_id = "6a6c9841-efcf-4bd9-b9ad-be7cf5fce5f8"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "curiocity-apex-storage"

[[kv_namespaces]]
binding = "curiocity_kv"
id = "2133cc6d43154955b6dcf0f491408d49" 